name: Deploy Compute Container
author: shaquillehinds
description: Builds the docker image from the dockerfie in this repository and deploys it to GCP Compute Engine as a container
inputs:
  project_id:
    description: The GCP project id for your container
    required: true
  image_name:
    description: The name of the inage you want to deploy
    required: true
  compute_instance_name:
    description: The name of the instance you're deploying to
    required: true
  compute_zone:
    description: The compute zone of the instance you're deploying to
    required: true
  docker_build_command:
    description: Enter you docker build command here
    required: true
  image_tag:
    description: (Optional) A custom tage for your image
    default: ${{github.sha}}
  service_account_json_key:
    description: The service account JSON key to allow github to perform actions on gcp on your behalf
    required: true
  instance_ssh_private_key:
    description: The ssh private key to the instance or project if the instance allows project wide keys
  instance_container_env:
    description: Any environment variables you want to pass to the instance. These won't be available on the build phase, only when the container is mounted as an instance. e.g PORT=3001,NODE_ENV=production
  machine_type:
    description: Specifies the machine type used for the instances. To get a list of available machine types, run 'gcloud compute machine-types list'. If unspecified, the default type is n1-standard-1
    default: e2-micro
  artifact_registry_location:
    description: The location of the artifact registry
    default: us-central1

runs:
  using: 'composite'
  steps:
    - uses: actions/checkout@v3

    - id: auth
      uses: google-github-actions/auth@v1
      with:
        credentials_json: '${{ inputs.service_account_json_key }}'

    - name: Setup Cloud SDK
      uses: google-github-actions/setup-gcloud@v1

    - name: Build Docker image
      shell: bash
      run: ${{ inputs.docker_build_command }}

    - name: Set Action Path (So updateInstance.sh can be found)
      run: echo "${{ github.action_path }}" >> $GITHUB_PATH
      shell: bash

    - name: Check Artifact Registry For Repository
      shell: bash
      run: checkRegistry.sh ${{inputs.image_name}} ${{inputs.artifact_registry_location}}

    - name: Set CONTAINER_IMAGE
      shell: bash
      run: echo "CONTAINER_IMAGE='${{inputs.artifact_registry_location}}-docker.pkg.dev/${{inputs.project_id}}/${{inputs.image_name}}-images/${{inputs.image_name}}'" >> $GITHUB_ENV

    - name: Push Docker Image to Artifact Registry
      shell: bash
      run: |-
        docker tag ${{inputs.image_name}}:latest ${{env.CONTAINER_IMAGE}}:latest
        docker tag ${{inputs.image_name}}:latest ${{env.CONTAINER_IMAGE}}:${{ inputs.image_tag || github.sha}}
        docker push ${{env.CONTAINER_IMAGE}}:latest
        docker push ${{env.CONTAINER_IMAGE}}:${{ inputs.image_tag || github.sha}}

    - name: Update/Create Compute Engine
      shell: bash
      run: updateInstance.sh ${{inputs.compute_instance_name}} ${{inputs.compute_zone}} ${{env.CONTAINER_IMAGE}}:${{ inputs.image_tag || github.sha}} ${{inputs.machine_type}} ${{inputs.instance_container_env}}

    - name: Clean Up Dangling images
      if: ${{ inputs.instance_ssh_private_key }}
      uses: google-github-actions/ssh-compute@v0
      with:
        instance_name: ${{inputs.compute_instance_name}}
        zone: ${{inputs.compute_zone}}
        ssh_private_key: '${{ inputs.instance_ssh_private_key }}'
        command: docker image prune -f
